/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NodeRepr {
  /**
   * Append a child node to this node, after existing children.
   *
   * The child node will be remove from its previous position.
   */
  append(newChild: NodeRepr): void
  appendChild(newChild: NodeRepr): NodeRepr
  removeChild(child: NodeRepr): NodeRepr
  /**
   * Prepend a child node to this node, before existing children.
   *
   * The child node will be remove from its previous position.
   */
  prepend(newChild: NodeRepr): void
  /**
   * Insert a new sibling after this node.
   *
   * The sibling node will be remove from its previous position.
   */
  after(newSibling: NodeRepr): void
  /**
   * Insert a new sibling before this node.
   *
   * The sibling node will be remove from its previous position.
   */
  before(newSibling: NodeRepr): void
  insertBefore(newNode: NodeRepr, refNode?: NodeRepr | undefined | null): NodeRepr
  /** Remove a node from its parent and siblings. Children are not affected. */
  remove(): void
  /** Assign an attribute K-V to this node */
  setAttribute(name: string, value: string): void
  /** Remove an attribute of this node by name. */
  removeAttribute(name: string): void
  toggleAttribute(name: string, force?: boolean | undefined | null): boolean
  setAttributeNS(namespace: string | undefined | null, name: string, value: string): void
  removeAttributeNS(namespace: string | undefined | null, localName: string): void
  createElement(tagName: string): NodeRepr
  createTextNode(data: string): NodeRepr
  createComment(data: string): NodeRepr
  createDocumentFragment(): NodeRepr
  createProcessingInstruction(target: string, data: string): NodeRepr
  importNode(externalNode: NodeRepr, deep?: boolean | undefined | null): NodeRepr
  adoptNode(externalNode: NodeRepr): NodeRepr
  replaceChild(newChild: NodeRepr, oldChild: NodeRepr): NodeRepr
  replaceWith(newNode: NodeRepr): void
  insertAdjacentElement(position: string, element: NodeRepr): NodeRepr | null
  insertAdjacentText(position: string, data: string): void
  insertAdjacentHTML(position: string, html: string): void
  normalize(): void
  splitText(offset: number): NodeRepr
  substringData(offset: number, count: number): string
  appendData(data: string): void
  insertData(offset: number, data: string): void
  deleteData(offset: number, count: number): void
  replaceData(offset: number, count: number, data: string): void
  get nodeType(): number
  get nodeName(): string
  get tagName(): string | null
  get namespaceURI(): string | null
  get prefix(): string | null
  get localName(): string | null
  get id(): string
  set id(id: string)
  get className(): string
  set className(className: string)
  get parentNode(): NodeRepr | null
  get firstChild(): NodeRepr | null
  get lastChild(): NodeRepr | null
  get previousSibling(): NodeRepr | null
  get nextSibling(): NodeRepr | null
  get parentElement(): NodeRepr | null
  get firstElementChild(): NodeRepr | null
  get lastElementChild(): NodeRepr | null
  get previousElementSibling(): NodeRepr | null
  get nextElementSibling(): NodeRepr | null
  get children(): Array<NodeRepr>
  get childElementCount(): number
  getRootNode(): NodeRepr
  get nodeValue(): string | null
  set nodeValue(value?: string | undefined | null)
  get data(): string | null
  set data(value: string)
  get textContent(): string
  set textContent(text: string)
  isSameNode(otherNode: NodeRepr): boolean
  get innerHTML(): string
  set innerHTML(html: string)
  get outerHTML(): string
  set outerHTML(html: string)
  get ownerDocument(): NodeRepr | null
  get childNodes(): Array<NodeRepr>
  get isConnected(): boolean
  get doctype(): NodeRepr | null
  get publicId(): string
  get systemId(): string
  get name(): string
  get target(): string
  classListAdd(className: string): void
  classListRemove(className: string): void
  classListToggle(className: string, force?: boolean | undefined | null): boolean
  classListContains(className: string): boolean
  datasetGet(): Record<string, string>
  datasetSet(key: string, value: string): void
  datasetRemove(key: string): void
  /** Get attribute value of this node by given name. */
  getAttribute(name: string): string | null
  getAttributeNames(): Array<string>
  hasAttributes(): boolean
  hasChildNodes(): boolean
  compareDocumentPosition(other: NodeRepr): number
  querySelector(selectors: string): NodeRepr | null
  querySelectorAll(selectors: string): Array<NodeRepr>
  getAttribute(name: string): string | null
  hasAttribute(name: string): boolean
  getAttributeNS(namespace: string | undefined | null, localName: string): string | null
  hasAttributeNS(namespace: string | undefined | null, localName: string): boolean
  lookupPrefix(namespace?: string | undefined | null): string | null
  lookupNamespaceURI(prefix?: string | undefined | null): string | null
  isDefaultNamespace(namespace?: string | undefined | null): boolean
  getElementById(id: string): NodeRepr | null
  getElementsByClassName(classNames: string): Array<NodeRepr>
  getElementsByTagName(tagName: string): Array<NodeRepr>
  contains(otherNode: NodeRepr): boolean
  isEqualNode(otherNode: NodeRepr): boolean
  get head(): NodeRepr | null
  get body(): NodeRepr | null
  get title(): string
  get documentElement(): NodeRepr | null
  matches(selectors: string): boolean
  closest(selectors: string): NodeRepr | null
  /** The node object, cann't be instantiated in javascript. So call the constructor will throw an error. */
  constructor(): void
  get elementNode(): number
  get attributeNode(): number
  get textNode(): number
  get cdataSectionNode(): number
  get entityReferenceNode(): number
  get entityNode(): number
  get processingInstructionNode(): number
  get commentNode(): number
  get documentNode(): number
  get documentTypeNode(): number
  get documentFragmentNode(): number
  get notationNode(): number
  get documentPositionDisconnected(): number
  get documentPositionPreceding(): number
  get documentPositionFollowing(): number
  get documentPositionContains(): number
  get documentPositionContainedBy(): number
  get documentPositionImplementationSpecific(): number
  cloneNode(deep?: boolean | undefined | null): NodeRepr
}
